bbs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from web import views
from webqq import urls as chat_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', views.index),
    url(r'^chat/', include(chat_urls)),
    url(r'^category/(\d+)/$',views.category, name='category'),
    url(r'^article_detail/(\d+)', views.article_detail, name='article_detail'),
    url(r'^acc_logout/', views.acc_logout, name='logout'),
    url(r'^acc_login/', views.acc_login, name='login'),
    url(r'^new_article', views.new_article, name='new_article'),
    url(r'add_comment', views.add_comment, name='add_comment'),

]

web/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    '''帖子表'''
    title = models. CharField(u"文章标题",max_length=255, unique=True)
    category = models.ForeignKey('Category',verbose_name=u"帖子板块", on_delete=models.CASCADE)
    head_img = models.ImageField(upload_to="uploads")
    summary = models.CharField(u"总结", max_length=225)
    content = models.TextField(u"文章内容")
    author = models.ForeignKey("UserProfile", verbose_name=u"作者",on_delete=models.CASCADE)
    publish_date = models.DateTimeField(u"日期", auto_now=True)
    hidden = models.BooleanField(u'是否隐藏', default=True)
    priority = models.IntegerField(u"优先级",default=1000)

    def __str__(self):
        return "%s, author:%s" %(self.title, self.author)


class Comment(models.Model):
    '''评论表'''
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
    #blank=True是django.admin可以为空;null=True是数据库可以为空
    parent_comment = models.ForeignKey('self', related_name='p_comment',blank=True, null=True, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s, user:%s" %(self.comment, self.user)

class ThumbUp(models.Model):
    '''点赞'''
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    user = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    def __str__(self):
        return "user:%s" %(self.user)

class Category(models.Model):
    '''帖子板块'''
    name = models.CharField(max_length=64,unique=True)
    admin = models.ManyToManyField('UserProfile')

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    '''用户信息'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=32)
    groups = models.ManyToManyField('UserGroup', blank=True, null=True)
    #symmetrical=默认对称
    friends = models.ManyToManyField('self', blank=True, related_name='my_friend')


    def __str__(self):
        return self.name

class UserGroup(models.Model):
    '''用户组'''
    name = models.CharField(max_length=64, unique=True)

    def __unicode__(self):
        return self.name

web/forms.py
from django import forms
import os
from .models import Comment

class ArticleForm(forms.Form):
    title = forms.CharField(max_length=255, min_length=1)
    summary = forms.CharField(max_length=255, min_length=1)
    head_img = forms.ImageField()
    category_id = forms.IntegerField()
    content = forms.CharField(min_length=10)

def handle_uploaded_file(request, f):
    base_img_upload_path = 'statics/imgs'
    user_path = '%s/%s' %(base_img_upload_path, request.user.userprofile.id)

    if not os.path.exists(user_path):
        os.makedirs(user_path)
    with open("%s/%s" %(user_path, f.name), 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    return "/static/imgs/%s/%s" %(request.user.userprofile.id, f.name)

class CommentForm(forms.Form):
    article_id = forms.IntegerField()
    comment = forms.CharField(min_length=2)

templates/article.html
{% extends 'index.html' %}
{% load custom_tags %}

{% block page-container %}
    <div class="article-detail">
        <h2>{{ article_obj.title }}</h2>
        <h3>{{ article_obj.content|safe }}</h3>

        <hr style="height: 1px;background-color: red"/>

        <div class="pl-mark-wrap">
            <span class="pl-yh-span-mark active" id="comment-pl-position">说点什么</span>
        </div>
        {% if request.user.is_authenticated %}
            <div class="author-info">
                <div class="author-face pl-yh-article-publish">
                    <img src="{{ article_obj.head_img }}">
                </div>
                <span class="author-name pl-yh-article-publish">{{ request.user.userprofile.name }}</span>
                <form class="comment-form" id="jsStayForm">{% csrf_token %}
                    <input name="article_id" type="hidden" id="js-name" value="{{ article_obj.id }}">
                    <textarea class="form-control  js-comment-yh-form-control" id="id_comment" name="comment" placeholder="客官，2个字起评，不讲价哟"></textarea>
                    <button class="btn" id="jsStayBtn">发表</button>
                </form>
            </div>
        {% else %}
            <div class="no-login-box ">
            <a href="{% url 'login' %}">登录</a>后参与评论
        </div>
        {% endif %}




        {% build_comment_tree article_obj.comment_set.select_related%}


    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<!-- saved from url=(0039)https://v3.bootcss.com/examples/navbar/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>草榴社区</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap_3.3.7_css_bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/bootstrap/css/navbar.css" rel="stylesheet">
    <link href="/static/bootstrap/css/custom.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <script src="/static/bootstrap/js/ie-emulation-modes-warning.js"></script>
    {% block head-css %}

    {% endblock %}

    {% block head-js %}

    {% endblock %}

  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">草榴社区</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/">综合区</a></li>
              <li><a href="{% url 'category' 1%}">欧美专区</a></li>
              <li><a href="{% url 'category' 2%}">日韩专区</a></li>
              <li><a href="{% url 'category' 3%}">武汉专区</a></li>
              <li><a href="{% url 'chat' %}">聊天室</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}


              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-haspopup="true" aria-expanded="false">{{ request.user.userprofile.name }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'new_article' %}">发帖</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="/#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="{% url 'logout' %}">注销</a></li>
                </ul>
              </li>
              {% else %}
                  <li><a href="{% url 'login' %}">注册/登录</a></li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
          {% block page-container %}
              <div class="row">
                  <div class="col-md-8 left-content-panel">
                      <div class="content-box">
                          {% for article in articles reversed %}
                              <div class="row article-box">
                                  <div class="col-md-4 article-head-image">
                                      <img src="{{ article.head_img }}"/>
                                  </div>
                                  <div class="">
                                      <div class="col-md-7 article-summary">
                                          <a href="{% url 'article_detail' article.id%}"><h4>{{ article.title }}</h4></a>
                                          <div class="acticle-attr">
                                              <ul class="list-inline">
                                                  <li>{{ article.author.name }}</li>
                                                  <li>{{ article.publish_date }}</li>
                                                  <li>点赞：{{ article.thumbup_set.select_related.count }}</li>
                                                  <li>评论：{{ article.comment_set.select_related.count }}</li>
                                              </ul>
                                          </div>
                                          <p>{{ article.summary }}</p>
                                      </div>
                                  </div>
                              </div>
                              <hr style="color: yellow">
                          {% endfor %}
                      </div>

                  </div>

                  <div class="col-md-4 right-side-bar">
                      right
                  </div>
              </div>
          {% endblock %}
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/bootstrap/js/jquery_1.12.4_jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/bootstrap/js/bootstrap_3.3.7_js_bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/bootstrap/js/ie10-viewport-bug-workaround.js"></script>
    <script src="/static/bootstrap/js/custom.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
        // {#    $("#navbar li").click(function () {#}
        // {##}
        // {#        $(this).siblings().removeClass("active");#}
        // {#        $(this).addClass("active");#}
        // {#    })#}


            var menus = $("#navbar a[href='{{ request.path }}']")[0];
            $(menus).parent().addClass("active");
            $(menus).parent().siblings().removeClass("active");

        })
    </script>

  {% block bottom-js %}

  {% endblock %}

</body>
</html>

templates/login.html
{% extends 'index.html' %}


{% block page-container %}
    <div class="container">

      <form class="form-signin" action="{% url 'login' %}" method="post">
          {% csrf_token %}
        <h2 class="form-signin-heading">用户登录</h2>
        <label for="inputEmail" class="sr-only">用户名</label>
        <input type="text" id="" name="username" class="form-control" placeholder="用户名" required="" autofocus="">
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="密码" required="">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> 记住我
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
          {% if err_msg %}
            <p style="color: red">{{ err_msg }}</p>
          {% endif %}

      </form>

    </div>


{% endblock %}

templates/new_article.html
{% extends 'index.html' %}

{% block head-js %}
    <script src="/static/plugins/ckeditor/ckeditor.js"></script>
{% endblock %}

{% block page-container %}
    <div class="new_article">
        <!--{#    这里必须加上enctype才能传多媒体文件#}-->
        {% if new_article_obj %}
            <h3>文章{{ new_article_obj.title }}已发布,<a href="{% url 'article_detail' new_article_obj.id %}">点我查看</a></h3>
        {% else %}
            <form enctype="multipart/form-data" method="post" action="new_article.html">{% csrf_token %}
                <input name="title" type="text" class="form-control" placeholder="文章标题">

                <select name="category_id" class="form-control">
                  {% for category in category_list %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                  {% endfor %}
                </select>

                <input name="summary" type="text" class="form-control" placeholder="文章简介">

                <input type="file" name="head_img">必选文章标题图片

                <textarea id="ck-editor" name="content" class="form-control" rows="3"></textarea>
                <br/>
                <button type="submit" class="btn btn-success pull-right">发帖</button>
            </form>
        {% endif %}

    </div>
{% endblock %}

{% block bottom-js %}
    <script>
        CKEDITOR.replace('ck-editor');

        CKEDITOR.editorConfig = function (config) {
            //config.language = 'es'
            config.uiColor = 'blue';
            config.height = 800;
            config.toolbarCanCollapse = true;
        };
    </script>
    {% endblock %}